name: esphome compile 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: 3.11

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: "${{ PYTHON_VERSION }}"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Verify configuration files
      run: |
        declare -a config_file
        for config_file in $(find tests -maxdepth 2 -type f \( -name "*.yaml" \) ); do
            echo Verifying ${config_file}
            esphome config ${config_file}
            echo Compiling ${config_file}
            esphome compile ${config_file}
        done
