name: esphome compile 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
    - name: Verify configuration files
      run: |
        declare -a config_file
        for config_file in $(find tests -maxdepth 2 -type f \( -name "*.yaml" \) ); do
            echo Verifying ${config_file}
            esphome config ${config_file}
            echo Compiling ${config_file}
            esphome compile ${config_file}
        done
